// DO NOT MODIFY THIS FILE.
// This entire file was automatically generated by class CreateUIConstantFiles.
// Make any needed changes in class CreateUIConstantFiles.

namespace ImprovedPieCharts
{
    // Constants for UI bindings.
    public class UIBindings
    {
        public const string GroupName = "ImprovedPieCharts";
        public const string ChartType = "ChartType";
        public const string PieChartSize = "PieChartSize";
        public const string PieChartHoleSize = "PieChartHoleSize";
        public const string BarChartHeight = "BarChartHeight";
        public const string ChartAnimation = "ChartAnimation";
    }

    // Defaults for mod settings.
    public class ModSettingsDefaults
    {
        public const ModSettings.ChartTypes ChartType = ModSettings.ChartTypes.PieChart;
        public const int PieChartSize = 125;
        public const int PieChartHoleSize = 60;
        public const int BarChartHeight = 25;
        public const bool ChartAnimation = true;
    }

    // Translation keys.
    public class UITranslationKey
    {
        public const string Title = "ImprovedPieCharts.Title";
        public const string Description = "ImprovedPieCharts.Description";

        public const string SettingTitle = "Options.SECTION[ImprovedPieCharts.ImprovedPieCharts.Mod]";
        public const string SettingGroupChartSettings = "Options.GROUP[ImprovedPieCharts.ImprovedPieCharts.Mod.ChartSettings]";
        public const string SettingChartSettingsDescription = "Options.OPTION[ImprovedPieCharts.ImprovedPieCharts.Mod.ModSettings.ChartSettingsDescription]";
        public const string SettingChartTypeLabel = "Options.OPTION[ImprovedPieCharts.ImprovedPieCharts.Mod.ModSettings.ChartType]";
        public const string SettingChartTypeDesc = "Options.OPTION_DESCRIPTION[ImprovedPieCharts.ImprovedPieCharts.Mod.ModSettings.ChartType]";
        public const string SettingChartTypePieChart = "Options.ImprovedPieCharts.ImprovedPieCharts.Mod.CHARTTYPES[PieChart]";
        public const string SettingChartTypeBarChart = "Options.ImprovedPieCharts.ImprovedPieCharts.Mod.CHARTTYPES[BarChart]";
        public const string SettingChartTypeNoChart = "Options.ImprovedPieCharts.ImprovedPieCharts.Mod.CHARTTYPES[NoChart]";
        public const string SettingPieChartSizeLabel = "Options.OPTION[ImprovedPieCharts.ImprovedPieCharts.Mod.ModSettings.PieChartSize]";
        public const string SettingPieChartSizeDesc = "Options.OPTION_DESCRIPTION[ImprovedPieCharts.ImprovedPieCharts.Mod.ModSettings.PieChartSize]";
        public const string SettingPieChartHoleSizeLabel = "Options.OPTION[ImprovedPieCharts.ImprovedPieCharts.Mod.ModSettings.PieChartHoleSize]";
        public const string SettingPieChartHoleSizeDesc = "Options.OPTION_DESCRIPTION[ImprovedPieCharts.ImprovedPieCharts.Mod.ModSettings.PieChartHoleSize]";
        public const string SettingBarChartHeightLabel = "Options.OPTION[ImprovedPieCharts.ImprovedPieCharts.Mod.ModSettings.BarChartHeight]";
        public const string SettingBarChartHeightDesc = "Options.OPTION_DESCRIPTION[ImprovedPieCharts.ImprovedPieCharts.Mod.ModSettings.BarChartHeight]";
        public const string SettingChartAnimationLabel = "Options.OPTION[ImprovedPieCharts.ImprovedPieCharts.Mod.ModSettings.ChartAnimation]";
        public const string SettingChartAnimationDesc = "Options.OPTION_DESCRIPTION[ImprovedPieCharts.ImprovedPieCharts.Mod.ModSettings.ChartAnimation]";
        public const string SettingResetSettingsLabel = "Options.OPTION[ImprovedPieCharts.ImprovedPieCharts.Mod.ModSettings.ResetSettings]";
        public const string SettingResetSettingsDesc = "Options.OPTION_DESCRIPTION[ImprovedPieCharts.ImprovedPieCharts.Mod.ModSettings.ResetSettings]";
        public const string SettingGroupAbout = "Options.GROUP[ImprovedPieCharts.ImprovedPieCharts.Mod.About]";
        public const string SettingModVersionLabel = "Options.OPTION[ImprovedPieCharts.ImprovedPieCharts.Mod.ModSettings.ModVersion]";
        public const string SettingModVersionDesc = "Options.OPTION_DESCRIPTION[ImprovedPieCharts.ImprovedPieCharts.Mod.ModSettings.ModVersion]";
    }
}
