// DO NOT MODIFY THIS FILE.
// This entire file was automatically generated by class CreateUIConstantFiles.
// Make any needed changes in class CreateUIConstantFiles.

// Constants for UI bindings.
export class UIBindings
{
    public static GroupName: string = "ImprovedPieCharts";
    public static ChartType: string = "ChartType";
    public static PieChartSize: string = "PieChartSize";
    public static PieChartHoleSize: string = "PieChartHoleSize";
    public static BarChartHeight: string = "BarChartHeight";
    public static ChartAnimation: string = "ChartAnimation";
}

// Chart types.
export class ChartTypes
{
    public static PieChart: number = 0;
    public static BarChart: number = 1;
    public static NoChart: number = 2;
}

// Defaults for mod settings.
export class ModSettingsDefaults
{
    public static ChartType: number = 0;
    public static PieChartSize: number = 125;
    public static PieChartHoleSize: number = 60;
    public static BarChartHeight: number = 25;
    public static ChartAnimation: boolean = true;
}
